### ISSUE TITLE
PDDL

### ISSUE THREAD

**Issue by Oscarvas** [Oscarvas/TFG#4]
Se propone hacer que el pddl de cada personaje solo contenga la información de lo que este conoce. Para ello hay que eliminar de este la información relativa a otros personajes que no nos sea de utilidad (el dragón deberá conocer la ubicación de la princesa, pero los caballeros no tienen por que conocer la ubicación de otros personajes)

**Prioridad Alta.**

**Comment by JuanOre** [comment]
Un caballero/héroe no debería saber donde esta la princesa para ir a rescatarla?

**Comment by Oscarvas** [comment]
Los objetivos de cada personaje han de cargarse desde el personaje, y no desde el mundo.

Cuando un caballero no puede cumplir su objetivo, debera intentar ir a su casa
