### ISSUE TITLE
Configuracion Raza

### ISSUE THREAD

**Issue by JuanOre** [Oscarvas/TFG#6]
Permitir configurar las razas a traves de un XML.
- Hacer el loader de las razas.
- Especificar para cada raza su nombre y atributos específicos.
- Ligar cada raza a una región del mapa.
- Modificar las referencias a las razas en el resto del codigo.

**Prioridad media alta.**

**Comment by Oscarvas** [comment]
De hecho, deberiamos desligar la raza a la region y explico el por que:

Si se da el caso de que al final el usuario decida modificar el mapa, no tiene por que poner un castillo en la region a la que pertenece la raza del rey que hubiese podido elegir.

Sería mas conveniente ligar el "nacimiento" de cada personaje en funcion del tipo de localizacion (esto pertenece a otra issue), y que la raza solo influya en los atributos del personaje
